


export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS"
export const BUY = "BUY"
export const CHECKOUT = "CHECKOUT"
export const LOAD_ORDER_SUCCESS = "LOAD_ORDER_SUCCESS"
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS"